-- =====================================================
-- Supabase 数据库初始化脚本
-- 博客站 (Blog) 专用表结构
-- =====================================================

-- 1. 创建博客文章表
CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  category TEXT NOT NULL CHECK (category IN ('diary', 'experience', 'work', 'notes')),
  cover TEXT,
  badge TEXT,
  badge_class TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  published BOOLEAN DEFAULT FALSE
);

-- 2. 创建索引优化查询性能
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_created_at ON blog_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published ON blog_posts(published);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category_published ON blog_posts(category, published);

-- 3. 创建配置表（如果不存在）
-- 注意：此表与 nav 项目共用，通过 key 区分
CREATE TABLE IF NOT EXISTS config (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 配置 Row Level Security (RLS)
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- 允许所有人读取已发布的文章
DROP POLICY IF EXISTS "Public read published posts" ON blog_posts;
CREATE POLICY "Public read published posts"
ON blog_posts FOR SELECT
USING (published = true);

-- 只有认证用户可以管理文章（管理员功能）
DROP POLICY IF EXISTS "Authenticated users manage posts" ON blog_posts;
CREATE POLICY "Authenticated users manage posts"
ON blog_posts FOR ALL
USING (auth.role() = 'authenticated');

-- 5. 插入示例文章（可选）
INSERT INTO blog_posts (title, excerpt, content, category, cover, badge, badge_class, published)
VALUES
(
  '【00】起点 · 给自己的一块写字地',
  '为什么要写博客？这是给自己的一个答案。',
  '# 为什么要写博客？

这是我的第一篇博客文章。作为一个产品经理，我一直在思考如何更好地记录自己的思考过程和工作经验。

博客不仅是一个输出平台，更是一个思考工具。通过写作，我可以：

1. **梳理思路**：把脑海中模糊的想法变成清晰的文字
2. **沉淀经验**：记录工作中的得失，方便日后回顾
3. **持续学习**：在写作过程中发现知识盲区，促进自我提升
4. **分享交流**：与同行交流想法，碰撞出新的火花

所以，这个博客就这样诞生了。

希望未来的自己，回头看这些文字时，能感受到当时的热情和思考。

Let''s start!',
  'diary',
  'https://images.unsplash.com/photo-1526498460520-4c246339dccb?auto=format&fit=crop&w=1600&q=80',
  '起点',
  'hero-badge--orange',
  true
);

-- 6. 创建更新时间自动触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_blog_posts_updated_at ON blog_posts;
CREATE TRIGGER update_blog_posts_updated_at
    BEFORE UPDATE ON blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 7. 初始化博客配置
INSERT INTO config (key, value, updated_at)
VALUES (
  'blog_config',
  '{"site_name": "毛毛的产品日记", "site_description": "永远相信美好的事即将发生", "author": "毛毛"}'::jsonb,
  NOW()
)
ON CONFLICT (key) DO NOTHING;

-- =====================================================
-- 设置完成！
--
-- 下一步：
-- 1. 在 Supabase Dashboard 的 SQL Editor 中执行此脚本
-- 2. 检查 Table Editor 确认表已创建
-- 3. 在项目中更新 SUPABASE_URL 和 SUPABASE_KEY
-- =====================================================
